// ============================================================================
// IMPORTANT!
// ----------------------------------------------------------------------------
// This file is automatically generated, do not edit it! Changes will be lost
// on the next build.
// Edit source file at "_build/templates/spec/runner_js.hbs" and run
// `node build pkg`
// ============================================================================


// for nodejs
var requirejs = requirejs || require('requirejs');


var specGroups = [
    'spec-array',
    'spec-collection',
    'spec-financial',
    'spec-function',
    'spec-lang',
    'spec-math',
    'spec-number',
    'spec-object',
    'spec-queryString',
    'spec-random',
    'spec-string',
    'spec-time'
];


if (jasmine) { //browser

    requirejs({
        baseUrl : 'spec',
        paths : {
            'amd-utils' : '../../src'
        },
        waitSeconds : (location.protocol === 'file:' || location.href.indexOf('://localhost') !== -1)? 5 : 45, //fail early locally
        urlArgs : 'bust='+ (+new Date())
    }, specGroups, function(){
        var reporter = new jasmine.HtmlReporter(),
            env = jasmine.getEnv();
        env.specFilter = function(spec){
            return reporter.specFilter(spec);
        };
        env.addReporter(reporter);
        env.execute();
    });

} else { // nodejs

    var jasmine = require('jasmine-node');
    // jasmine-node doesn't expose the TerminalReporter :(
    var Reporter = require('jasmine-node/lib/jasmine-node/reporter').jasmineNode.TerminalReporter;
    var reporter = new Reporter({
        color: true
    });
    var env = jasmine.getEnv();
    requirejs({
        baseUrl : __dirname + '/spec',
        nodeRequire : require,
        paths : {
            'amd-utils' : '../../src'
        }
    }, specGroups, function(){
        env.addReporter(reporter);
        env.execute();
    });

}

