define([
   'array/spec-compact',
   'array/spec-contains',
   'array/spec-every',
   'array/spec-filter',
   'array/spec-forEach',
   'array/spec-indexOf',
   'array/spec-isSparse',
   'array/spec-join',
   'array/spec-lastIndexOf',
   'array/spec-map',
   'array/spec-range',
   'array/spec-reduce',
   'array/spec-reduceRight',
   'array/spec-remove',
   'array/spec-removeAll',
   'array/spec-some',
   'array/spec-shuffle',
   'array/spec-unique'
], function(){
    //noop
});
