//automatically generated, do not edit!
//run `node build` instead
define([
    'string/spec-replaceAccents',
    'string/spec-rpad',
    'string/spec-escapeRegExp',
    'string/spec-lowerCase',
    'string/spec-escapeHtml',
    'string/spec-removeNonWord',
    'string/spec-normalizeLineBreaks',
    'string/spec-hyphenate',
    'string/spec-unescapeHtml',
    'string/spec-makePath',
    'string/spec-underscore',
    'string/spec-ltrim',
    'string/spec-pascalCase',
    'string/spec-removeNonASCII',
    'string/spec-trim',
    'string/spec-truncate',
    'string/spec-slugify',
    'string/spec-contains',
    'string/spec-properCase',
    'string/spec-repeat',
    'string/spec-camelCase',
    'string/spec-stripHtmlTags',
    'string/spec-typecast',
    'string/spec-crop',
    'string/spec-unCamelCase',
    'string/spec-sentenceCase',
    'string/spec-startsWith',
    'string/spec-endsWith',
    'string/spec-unhyphenate',
    'string/spec-rtrim',
    'string/spec-upperCase',
    'string/spec-lpad',
    'string/spec-interpolate'
], function(){
    //noop
});
