define([
    'string/spec-camelCase',
    'string/spec-crop',
    'string/spec-hyphenate',
    'string/spec-ltrim',
    'string/spec-makePath',
    'string/spec-pascalCase',
    'string/spec-properCase',
    'string/spec-removeNonASCII',
    'string/spec-removeNonWord',
    'string/spec-replaceAccents',
    'string/spec-rtrim',
    'string/spec-sentenceCase',
    'string/spec-stripHtmlTags',
    'string/spec-toSlug',
    'string/spec-trim',
    'string/spec-truncate',
    'string/spec-typecast',
    'string/spec-unCamelCase',
    'string/spec-unHyphenate'
], function(){
    //todo
});
